---
title: "area_graph2"
author: "Anna Calle"
date: "2/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
# For app

  ### Second Bar Graph ### 
  
  # Create vector with input names
  input_names <- c("Min SST",
                   "Max SST",
                   "Depth",
                   "Current Velocity",
                   "Distance to Shore",
                   "Dissolved Oxygen",
                   "MPAs",
                   "Reefs",
                   "Artificial Reefs",
                   "Oil Pipelines",
                   "Oil Production",
                   "Shipping Lanes")
  
  
  # Create vector with number of 0 cells in each binary raster
  freq_0 <- reactive(c(
    freq(sst_binary_min(), value = 0),
    freq(sst_binary_max(), value = 0),
    freq(depth_binary(), value = 0),
    freq(current_binary(), value = 0),
    freq(dist_shore_binary(), value = 0),
    freq(DO_min_binary(), value = 0),
    freq(mpas_binary(), value = 0),
    freq(reefs_binary(), value = 0),
    freq(reefs_artificial_binary(), value = 0),
    freq(og_pipeline_binary(), value = 0),
    freq(og_production_binary(), value = 0),
    freq(shipping_lanes_binary(), value = 0)
  ))
  
  # Create df with layer names, frequency of 0 cells, and percentage of excluded area
  area_df <- reactive(
    data.frame(input_names, freq_0()) %>% 
      mutate(percent_excluded = round(freq_0()*100/30959, digits = 2)) %>% 
      arrange(percent_excluded) %>% 
      mutate( input_names = factor(input_names, levels = input_names))
  )
  

  # Create percentage excluded plot
    excluded_plot <- reactive({
      ggplot(area_df(), aes(x = input_names, y = percent_excluded)) +
      geom_col(fill = "darkturquoise") +
      coord_flip() +
      ylab("Percentage of EEZ Excluded") +
      xlab("") +
      scale_y_continuous( expand = c(0,0)) +
      theme_classic(14) +
      geom_text(
        aes(label = paste0(percent_excluded,"%"), y = percent_excluded + 15), 
        color = "black", 
        size = 5,
        hjust = 1
      )
      
    })
    
    # A temp file to save the output.
    # This file will be removed later by renderImage
    outfile_name <- reactive(
      tempfile(pattern = paste0("image", input$run_button),  fileext = '.png')
    )
    
    
    # Generate the PNG
    reactive({
      png(outfile_name(), width = 400, height = 300)
      excluded_plot()
      dev.off()
    })
    
    # Create empty reactive values
    values$outfile <- vector()
```

