---
title: "Distance to Shore"
author: "Sandra Fogg"
date: "11/18/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
# Load packages
library(rnaturalearth)
library(beepr)
```

Create a Raster for Distance to Shore
```{r}
# Import Brazil Data from the "rnaturalearth" Package
bound_BRA <- ne_countries(scale = 110, country = "Brazil", returnclass = "sf")%>% 
  sf::st_crop(eez_BRA)

# Plot Boundaries
plot(bound_BRA)

# Set the Extent to Brazil EEZ
extent <-extent(eez_BRA)

# Set the Cell Size Resolution to Bio-Oracle
res = res(min_sst_BRA)

# Create an Empty Raster for Distance to Shore Mask
blank_raster <- raster( extent, resolution = res)

# Rasterize the Coastline
rasterized_coast <- rasterize(bound_BRA, blank_raster, 43601)

# Plot Rasterized Coast
plot(rasterized_coast)

# Calculate the Distance to the Nearest Non-NA Pixel
distance_nonNA <- distance(rasterized_coast)
beep()

# Export the Raster as .tif
writeRaster(x = distance_nonNA, filename = paste0(path,"/distance_to_shore2.tif"), overwrite = F)

# Plot Distance Raster
plot(distance_nonNA)
```

Create a Land Value NA Mask and Raster
```{r}

# Create a Mask to Set Land Pixels to NA
dist_mask <- mask(is.na(rasterized_coast), rasterized_coast, maskvalue = 1, updatevalue = NA)

# Plot Mask
plot(dist_mask)

# Set Non-Land Pixels to NA (That way it is distance to land, not distance to non-land) ?
#dist_mask_reverse <- (((distance_nonNA*dist_mask)/1000)/1.854)

writeRaster(x = dist_mask, filename = paste0(path,"/distance_mask.tif"), overwrite = F)
```